apiVersion: apps/v1
kind: Deployment
metadata:
  name: musango
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musango
  template:
    metadata:
      labels:
        app: musango
    spec:
      containers:
      - name: musango
        image: hilltopconsultancy/musango:v1
        ports:
        - containerPort: 8082
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/musango-express"
        - name: PORT
          value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: musango
spec:
  type: NodePort
  selector:
    app: musango
  ports:
    - protocol: TCP
      port: 8082         # Service port
      targetPort: 8082   # Container port
      nodePort: 30012    # External access port